### PR TITLE
Fix display on raspberry pi with bigger buttons

### PR DESCRIPTION
**Pull request by jomarin38**
image

### CODE REVIEW

**Comment by sdaviet** [comment]
In the previous version, you have a label for the 0 Flight who inform. Where is this label now ? under Penalty label ?

**Comment by sdaviet** [comment]
Concerning Penalty label, no comments. I found it. it's great :)

**Comment by jomarin38** [comment]
The "0 filght" label is placed under the status label.
I moved it there because there was plenty of unused space there.
We could also place it below the penalty label if you prefer.

**Comment by sdaviet** [comment]
it's ok. Great.

**Pull request merged**
